name: Wheel Build

on:
  # Push with tag: build package and upload it to PyPI
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  wheel-build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-deps
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-deps.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install library
        run: poetry install --no-interaction

      - name: Run wheel build
        run: poetry build

      - name: Upload wheel data if the Git tag is set
        if: ${{ contains(github.ref, '/tags/') }}
        run: |
          poetry config pypi-token.pypi ${{ secrets.TWINE_PASSWORD_MNISQ }}
          poetry publish